name: CI
on: [push, pull_request]

jobs:
  build_test:
    name: Build and Test
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Setup Python ${{ matrix.python }}
      uses: actions/setup-python@v3.1.0
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run Tests
      run: ./run_tests
